# Generated by Django 5.2.1 on 2025-09-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category_master',
            new_name='CategoryMaster',
        ),
    ]
