# Generated by Django 5.2.1 on 2025-09-17 08:54

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_category_master_categorymaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='CatImage',
            field=models.ImageField(upload_to='category/'),
        ),
    ]
