# Generated by Django 5.2.1 on 2025-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_headersettings_navmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
