# Generated by Django 5.2.1 on 2025-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_articale_master_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
