# Generated by Django 5.2.1 on 2025-09-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_articale_master_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_super_user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Parson',
        ),
        migrations.DeleteModel(
            name='result',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
