# Generated by Django 5.2.1 on 2025-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_admin_super_user_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
