# Generated by Django 5.2.1 on 2025-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_trendingtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trendingtag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
