# Generated by Django 5.2.1 on 2025-09-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_trendingtag_created_at_alter_trendingtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtag',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='tags', to='myapp.articale_master'),
        ),
    ]
