# Generated by Django 5.2.1 on 2025-10-01 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trendingtag_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtag',
            name='slug',
            field=models.SlugField(unique=True, default=uuid.uuid4, editable=False),
        ),
    ]
