# Generated by Django 5.2.1 on 2025-10-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_trendingtag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingtag',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='trendingtag',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='trendingtag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trendingtag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
