# Generated by Django 5.2.1 on 2025-10-01 08:45

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_trendingtag_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
