# Generated by Django 5.2.1 on 2025-10-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_trendingtag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
