# Generated by Django 5.2.1 on 2025-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_trendingtag_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='myapp.trendingtag'),
        ),
    ]
