# Generated by Django 5.2.1 on 2025-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_articale_master_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='CatSlug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
