# Generated by Django 5.2.1 on 2025-10-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_articale_master_slug_alter_categorymaster_catslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articale_master',
            name='trending_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
