# Generated by Django 5.2.1 on 2025-10-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_articale_master_is_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale_master',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
