# Generated by Django 5.2.1 on 2025-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_articale_master_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articale_master',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
