# Generated by Django 5.2.1 on 2025-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_articale_master_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articale_master',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
